---

# This is close to the standard pipeline, except there’s an extra step in the
# middle to compile front-end assets.
#
# I tried adding this to the first step, but it usually choked with no actually error message (maybe it hit a secret time limit?)
#
# based on http://robbieminshall.blogspot.de/2015/06/forking-pipelines.html
# docs at https://www.ng.bluemix.net/docs/manageapps/deployingapps.html#sharetextpipelines

stages:
- name: Install & Compile
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: install & build assets
    type: builder
    build_type: npm
    script: |-
      #!/bin/bash
      npm install
      npm run build
- name: Deploy
  inputs:
  - type: job
    stage: Install & Compile
    job: install & build assets
  triggers:
  - type: stage
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"

      # View logs
      #cf logs "${CF_APP}" --recent
